# Site settings
title: Go Project Lab
safe:           false
source:         app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false

baseurl: "/ifrcgo_v2"

permalink: pretty

collections:
  events:
    output: true

# locale settings
default_locale:     "en"
authorized_locales: ["en"]

# add support for an atom feed
gems:
  - jekyll-feed

#page generator for appeals
# page_gen-dirs: true
page_gen:
  - data: 'appealsplus'
    template: 'build/appeals'
    name: 'meta_id'
    dir: 'appeals'
